
server:
  shutdown: graceful
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8
  port: 8888 # 9999

spring:
  application:
    name: hotel-mono-api
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(TW5Ru+JEnQXN78acqNe4OQP1W3W8pmPZ)
    password: ENC(kaKrvVahaZiiyYNDM7xCh5M3DPyVAtiy)
    url: ENC(orAfzV4Q6NOi+SsFCpCLV0KSkNcHbkq00r2tmFCR7vfQ4TnF69svWQIFdp6ELiAu)
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: true
    show_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  graphql:
    path: /graphql
    graphiql:
      path: /graphiql
      enabled: true
    schema:
      locations: classpath:graphql/**/
      file-extensions: .graphqls,.gqls
      introspection:
        enabled: true
        printer:
          enabled: true
    websocket:
      connection-init-timeout: 60s
      path:
    rsocket:
      mapping:
    cors:
      allow-credentials:
      allowed-headers:
      allowed-methods:
      allowed-origin-patterns:
      allowed-origins:
      exposed-headers:
      max-age: 1800s

management:
  endpoints:
    web:
      exposure:
        include: '*'
        # exclude: threaddump, heapdump
  endpoint:
    health:
      show-details: always

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: A421080gsm

springdoc:
  swagger-ui:
    path: swagger.html #http://localhost:8080/swagger.html 로 호출
  #  packages-to-scan:
  #    - cf.portal
  #    - cf.sysmgt.func
  #    - cf.comfunc.func
  override-with-generic-response: false # Default 응답 메시지(@ControllerAdvice) 제외
  default-produces-media-type: application/json

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: /app/logs/hotel-backend-log.log
  logback:
    rollingpolicy:
      file-name-pattern: "/app/logs/hotel-backend-log.%d{yyyy-MM-dd}.%i"
      max-history: 30
  level:
    org: INFO
    com: INFO
    cf: DEBUG