name: CI-CD

on:
  push:
    branches:
      - main
  
permissions:
  contents: read
  
jobs:
  CI-CD:
    runs-on: ubuntu-20.04
    steps:
    ## jdk setting
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # https://github.com/actions/setup-java
            
      - name: Build App
        run: ./gradlew build
        
      ## gradle caching
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Deploy Prod use SCP
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "server-api/build/libs/server-api-1.0.0.jar, server-batch/build/libs/server-batch-1.0.0.jar"
          target: "/app/hotel-mono-reservation"
          strip_components: 2

  deploy:
    needs: CI-CD
    runs-on: ubuntu-20.04
    steps:
      - name: Execute Server Init Script
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop: true
          script: |
            sh /app/hotel-mono-reservation/start_server.sh
            sleep 5
            ps -ef | grep server-api-1.0.0.jar | grep java
            
  ## time
  current-time:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH:mm:ss
          utcOffset: "+09:00" # 기준이 UTC이기 때문에 한국시간인 KST를 맞추기 위해 +9시간 추가

      - name: Print Current Time
        run: echo "Current Time=${{steps.current-time.outputs.formattedTime}}" # current-time 에서 지정한 포맷대로 현재 시간 출력
        shell: bash
